### ISSUE TITLE
Can't compile using gcc-arm-none-eabi Ubuntu 14.04

### ISSUE THREAD

**Issue by canximan** [ARMmbed/dfu-bootloader#3]
I'm trying to compile this for my NRF51-DK but I got a lot of error, Could you please show me how to compile this, I'm new with the bootloader.

Thanks you.

**Comment by rgrover** [comment]
Refer to https://developer.mbed.org/forum/team-63-Bluetooth-Low-Energy-community/topic/5201/
You may find that some of the documentation is outdated and that our use of the nRF-SDK has evolved to more recent versions. You'll have to account for that.

**Comment by rgrover** [comment]
Sorry, I shouldn't have closed this ticket without hearing back from you.

**Comment by LiyouZhou** [comment]
Hi @seedceo I built this not so long ago by following instructions [here](https://docs.mbed.com/docs/ble-intros/en/latest/Advanced/Bootloader/). I can't remember encountering any major problems. I used `armcc` thou. If you keep getting stuck, can you please post the command you used and the error you are seeing please?

**Comment by rgrover** [comment]
To carry @LiyouZhou's comment further: armcc was used because the arm-toolchain does a better job at creating smaller binaries. The bootloader currently needs to fit within 16K of flash. GCC was unable to achieve this in the past, perhaps that's no longer true.

The document I pointed you to should explain the technicalities. You're not restricted to 16K; you can aim for a larger bootloader if you update the system configuration appropriately--i.e. the softdevice neds to know where the bootloader resides so that it can forward control to it. I believe this is done through UIFCR (or something similar).

**Comment by datnguyencse** [comment]
Thanks you @rgrover  and @LiyouZhou for the link, I'm unable to use armcc because of the license. 
I will try https://developer.mbed.org/forum/team-63-Bluetooth-Low-Energy-community/topic/5201/ tomorrow.
Thanks you very much.
